# Configuration
# https://jekyllrb.com/docs/configuration/

theme: minima
repository: FriendsOfREDAXO/community
plugins: ['jekyll-seo-tag']
timezone: Europe/Berlin

# SEO
# https://github.com/jekyll/jekyll-seo-tag
title: REDAXO Community World Map
description: A map filled with people being involved in REDAXO CMS. Hosted at GitHub, which allows for everyone to add their map entries. Join us!

# Assets
# https://jekyllrb.com/docs/assets/
sass:
    style: compressed

# Collections
# https://jekyllrb.com/docs/collections/
collections:
- directory

# Exclude directories and/or files from the conversion.
# https://jekyllrb.com/docs/configuration/
exclude:
- CONTRIBUTE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- SETUP.md

# Compress HTML in Jekyll
# http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
